version: '3'

services:
  web:
    build: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/letsencrypt
      - ./data:/data
    depends_on:
      - certbot
    command: /bin/sh -c "sleep 10; nginx -g 'daemon off;'"

  certbot:
    image: certbot/certbot
    volumes:
      - ./certs:/etc/letsencrypt
      - ./data:/data
    command: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    entrypoint: "/bin/sh -c 'trap exit TERM; certbot renew || certbot certonly --webroot --webroot-path=/data/certbot --email your-email@example.com --agree-tos --no-eff-email -d actradev.com -d www.actradev.com'"
