  version: '3'

  services:
    web:
      build: .
      ports:
        - "80:80"
        - "443:443"
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
        - ./certs:/etc/letsencrypt
        - ./data:/data
      depends_on:
        - certbot

    certbot:
      image: certbot/certbot
      volumes:
        - ./certs:/etc/letsencrypt
        - ./data:/data
      command: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
